"""add agent_runs table

Revision ID: c042c144ac96
Revises: 7376c9eee5ed
Create Date: 2026-03-04 09:09:21.051382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c042c144ac96'
down_revision: Union[str, Sequence[str], None] = '7376c9eee5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('scanned', sa.Integer(), nullable=True),
    sa.Column('candidates_considered', sa.Integer(), nullable=True),
    sa.Column('signals_created', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_runs_started_at', 'agent_runs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_agent_runs_started_at', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
